### ISSUE TITLE
Renewal is failed with "cert.pem to be a symlink"

### ISSUE THREAD

**Issue by leranp** [linuxserver/docker-swag#129]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Renew without any problem
## Current Behavior

Renewal isn't work
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** Rasbian
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:** docker compose

## Command used to create docker container (run/create/compose/screenshot)

```
  swag:
     image: linuxserver/swag
     container_name: swag
     restart: unless-stopped
     cap_add:
       - NET_ADMIN
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Asia/XXX
       - URL=XXX.duckdns.org
       - SUBDOMAINS=
       - VALIDATION=duckdns
       - DUCKDNSTOKEN=XXXXXXXXXXXXX
       - EMAIL= XXXXX@gmail.com 
     volumes:
       - ./letsencrypt:/config
       - /etc/localtime:/etc/localtime:ro
     ports:
       - 443:443
```
## Docker logs

```
cronjob running on Fri May 21 02:08:01 IDT 2021
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/XXX.duckdns.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 70, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 468, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 538, in _check_symlinks
    raise errors.CertStorageError(
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/XXX.duckdns.org/cert.pem to be a symlink
Renewal configuration file /etc/letsencrypt/renewal/XXX.duckdns.org.conf is broken. Skipping.

```

I didn't change anything in the XXX.duckdns.org.conf file , this is the configuration:
```
# renew_before_expiry = 30 days
version = 1.12.0
archive_dir = /etc/letsencrypt/archive/XXX.duckdns.org
cert = /etc/letsencrypt/live/XXX.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/XXX.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/XXX.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/XXX.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = XXXXXXXXX
rsa_key_size = 4096
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = manual
manual_auth_hook = /app/duckdns-txt
post_hook = if ps aux | grep [n]ginx: > /dev/null; then s6-svc -h /var/run/s6/services/nginx; fi;     cd /config/keys/letsencrypt &&     openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: &&     sleep 1 &&     cat privkey.pem fullchain.pem > priv-fullchain-bundle.pem &&     chown -R abc:abc /config/etc/letsencrypt

```

**Comment by leranp** [comment]
> We don't really support symlinkng the cert out from any folder, cause it gives the error you just got. This is the best, and supported

I didn't changed anything in the certs files , there is cert.pem in this location , but he is not a symlink

**Comment by aptalca** [comment]
You likely incorrectly copied or restored the config folder and broke the symlinks. Delete the folder `/config/etc/letsencrypt` and restart

**Comment by leranp** [comment]
> You likely incorrectly copied or restored the config folder and broke the symlinks. Delete the folder `/config/etc/letsencrypt` and restart

Thanks, it work, but I am not sure if in the next renewal it will renew automatic without delete all this files
