### ISSUE TITLE
[BUG] ? AttributeError: module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by Flyingfufu** [linuxserver/docker-swag#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following upgrade of the container to the latest version, I get the following error lines endless after container start :

2023-01-23T22:22:18.307150323Z Traceback (most recent call last):
2023-01-23T22:22:18.307167888Z   File "/geoip2influx/geoip2influx.py", line 17, in <module>
2023-01-23T22:22:18.307204683Z     from IPy import IP as ipadd
2023-01-23T22:22:18.307217002Z   File "/usr/lib/python3.10/site-packages/IPy.py", line 1025, in <module>
2023-01-23T22:22:18.307483020Z     class IPSet(collections.MutableSet):
2023-01-23T22:22:18.307503132Z AttributeError: module 'collections' has no attribute 'MutableSet'

geoip2influx is not starting ever since according to the log file,  but Swag instance "seems" however to work fine.

### Expected Behavior

Get the instance running without this error

### Steps To Reproduce

Following upgrade of the container to the latest version, I get the following error lines endless after container start :

2023-01-23T22:22:18.307150323Z Traceback (most recent call last):
2023-01-23T22:22:18.307167888Z   File "/geoip2influx/geoip2influx.py", line 17, in <module>
2023-01-23T22:22:18.307204683Z     from IPy import IP as ipadd
2023-01-23T22:22:18.307217002Z   File "/usr/lib/python3.10/site-packages/IPy.py", line 1025, in <module>
2023-01-23T22:22:18.307483020Z     class IPSet(collections.MutableSet):
2023-01-23T22:22:18.307503132Z AttributeError: module 'collections' has no attribute 'MutableSet'

geoip2influx is not starting ever since according to the log file

Swag instance "seems" however to work fine.

Any idea how to fix it is welcome

### Environment

```markdown
- How docker service was installed: Docker stack via Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
image: lscr.io/linuxserver/swag: latest
environment:
  - DOCKER_MODS=linuxserver/mods:swag-geoip2influx|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-maxmind
```

### Container logs

```bash
-
```

**Comment by cahuete95** [comment]
hi all,

same error here since 2023-01-21 20:49 (Brusselstime).
Even if i suspect a docker image update, i found no root cause.
Neither with mod update because https://github.com/linuxserver/docker-mods/tree/swag-geoip2influx has no change since September 🤔

**Comment by cahuete95** [comment]
A little up for this subject that prevent the mod to work 😊
any update on it?
