### ISSUE TITLE
[BUG] unable to use dns challenge for porkbun registrar

### ISSUE THREAD

**Issue by ksurl** [linuxserver/docker-swag#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

porkbun dns validation fails with api key for creating txt record

### Expected Behavior

dns validation succeeds and cert is generated

### Steps To Reproduce

set api key and secret api key in /config/dns-conf/porkbun.ini
dns_porkbun_key="pk1_abc"
dns_porkbun_secret="sk1_abc"

run docker compose up and let init generate txt record to validate domain and generate

I have manually validated the api key and secret api key with a curl command and it successfully creates a TXT record on the domain DNS records.

```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{ 
    "apikey" : "MY_API_KEY",
    "secretapikey" : "MY_SECRET_KEY",
    "name" : "example",
    "type" : "TXT",
    "content" : "abc",
    "ttl" : "600"
  }' \
  https://porkbun.com/api/json/v3/dns/create/DOMAIN.com
```

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: docker install script from https://get.docker.com
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    networks:
      swag:
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Utc
      - URL=DOMAIN.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=porkbun
      - ONLY_SUBDOMAINS=true
      - STAGING=true
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  swag:
```

### Container logs

```bash

/var/log/letsencrypt/letsencrypt.log

2023-08-06 11:49:07,809:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-08-06 11:49:07,809:INFO:certbot._internal.auth_handler:dns-01 challenge for DOMAIN.com
2023-08-06 11:49:13,214:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/lsiopy/lib/python3.11/site-packages/certbot_dns_porkbun/cert/client.py", line 91, in _perform
    canonical_name = resolver.canonical_name(domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/dns/resolver.py", line 1640, in canonical_name
    return get_default_resolver().canonical_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/dns/resolver.py", line 1482, in canonical_name
    answer = self.resolve(name, raise_on_no_answer=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/dns/resolver.py", line 1321, in resolve
    timeout = self._compute_timeout(start, lifetime, resolution.errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/dns/resolver.py", line 1075, in _compute_timeout
    raise LifetimeTimeout(timeout=duration, errors=errors)
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.401 seconds: Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.

docker stdout log:
Requesting a certificate for *.DOMAIN.com
Unsafe permissions on credentials configuration file: /config/dns-conf/porkbun.ini
Unsafe permissions on credentials configuration file: /config/dns-conf/porkbun.ini
Encountered exception during recovery: KeyError: '<ERROR CODE>'
An unexpected error occurred:
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.401 seconds: Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.
```

**Comment by nemchik** [comment]
You could try increasing your propagation time

```yaml
    environment:
      - PROPAGATION=120
```

See if that makes a difference.

**Comment by ksurl** [comment]
I confirm this is an upstream issue with teh dns-certbot-porkbun plugin. I ran the maintainers docker image for infinityofspace/certbot_dns_porkbun and got the same error. I'll try increasing propagation time (though that time i had set it to 60 sec and it failed within 10s)

**Comment by ksurl** [comment]
seems to be a docker dns issue. this works fine when dns is on cloudflare but not porkbun (tested with same and different domains on each).

**Comment by ksurl** [comment]
It works if setting dns on the compose file to a public server like 1.1.1.1 so something is up with my local dns resolver. I'll close it since it is not a swag issue.

**Comment by ksurl** [comment]
it works on the infinityofspace/certbot_dns_plugin image but not swag for the domain I'm using (complains now that it's an invalid domain, set dns to 1.1.1.1)

**Comment by Gordi90** [comment]
I don't know why it is Done, it's still an active issue. (just run into it)

**Comment by nemchik** [comment]
> I don't know why it is Done, it's still an active issue. (just run into it)

Open a new issue, provide all the required info (opening an issue will prompt you to provide everything we need to help).

**Comment by ksurl** [comment]
> I don't know why it is Done, it's still an active issue. (just run into it)

I gave up and went back to cloudflare
